### ISSUE TITLE
ConcurrentModificationException on World Load [1.12.2]

### ISSUE THREAD

**Issue by Nanabell** [comp500/demagnetize#12]
Hello,
I've been playing a modified version of [DDnSS](https://www.curseforge.com/minecraft/modpacks/dungeons-dragons-and-space-shuttles) additional to a few others i have added Demagnetize as well.
Everything was working super smooth until i restarted my game after updating the pack today, which has updated the Forge version to `forge-14.23.5.2847`. 
After attempting to load up my save the Internal Single-player Server crashed (crash-log attached below). 

Creating a completely new world was working without any issues. 
After some trial runs i found out that Demagnetize was causing the Issue, after removing the mod the save loaded without any issues. 
Now, since i didn't want to play without it i attempted to save the world without Demagnetized installed and load it again installed. To remove any remains of it i was blessed with success!

So further testing was necessary to find when exactly the error would occur. 
Next was restarting the whole game without any changes which also crashed the server.
So it was not that mods are being added, which i had originally suspected.

 Then i remembered that i had white-list filters set in both of my Demagnetizers, so after restarting the game 3 more times to remove -> re-add without filters -> and restart again to check, my 3rd time loading the world greeted me with the same error again.

Some things i noticed when i created new instance with just bare bones setup of the modpack so i don't have to wait 5-min between each restart:
- it doesn't crash...
- it resets the Demagnetizers settings (filter and whitelist back to blacklist)
- console logs errors instead of crashing in the small version
```
20:19:12.347 | net.minecraft.tileentity.TileEntity | Server thread | Failed to create block entity demagnetize:demagnetizertile
20:19:12.348 | FML                                 | Server thread | A TileEntity demagnetize:demagnetizertile(link.infra.demagnetize.blocks.DemagnetizerTileEntity) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
20:19:12.348 | net.minecraft.tileentity.TileEntity | Server thread | Skipping BlockEntity with id demagnetize:demagnetizertile
```
- Errors appear on World reload not just Game restart
- This does **not** happen with the Advanced Demagnetizer

After restarting my main game and placing Advanced Demganetizers instead of the Base version and reloading the World worked without any problems. So i'll just be using the advanced ones for the time being :)

I hope this helps with finding the root of the problem.

mc-verison: 1.12.2
crash-log: [crash-2019-11-29_19.31.44-server](https://shuvi.is-a-good-waifu.com/3iE4nrf.txt)
forge: forge-14.23.5.2847

**Comment by comp500** [comment]
Interesting, could you send me your debug.log file from the small pack (where it errors)?

**Comment by Nanabell** [comment]
Here is the [latest.log](https://shuvi.is-a-good-waifu.com/9Hdk8t9.log). Hope this is what you need. Im not sure how to enable the "debug" log entries?

**Comment by comp500** [comment]
It's a separate file, but don't worry - I think that latest.log file has the information I need, thanks!

**Comment by comp500** [comment]
I'm not exactly sure what's going on in the larger pack, but I think I've fixed the issue in the smaller pack. Could you try it with this file? (unzip it first - GitHub only lets me upload zip files for some reason)
[demagnetize-1.12.2-1.1.0-patch.jar.zip](https://github.com/comp500/Demagnetize/files/3906532/demagnetize-1.12.2-1.1.0-patch.jar.zip)

**Comment by Nanabell** [comment]
Thank you so much,
the patched version fixed the small and large pack 👍 
Feel free to close or leave open if you plan to reference close this with a commit

**Comment by comp500** [comment]
Thanks for reporting it!
