### ISSUE TITLE
Requesting Support for ReWired [1.12]

### ISSUE THREAD

**Issue by Federsavo** [comp500/demagnetize#13]
I would like that the Ender-Convergence Device from the addon for Robotic Parts worked with this mod.

Link to the mod: [https://www.curseforge.com/minecraft/mc-mods/rewired](https://www.curseforge.com/minecraft/mc-mods/rewired)

**Comment by comp500** [comment]
It looks like an attempt to support the tag this mod uses was attempted, but there is a bug in the implementation. I have submitted a pull request here: https://github.com/mallrat208/Re-WIRED/pull/14

**Comment by Federsavo** [comment]
Hey,
Just wanted to let you know that last update of ReWired has support for Demagnetize (I think he doesn't update github anymore but I tested in a private world and it works)
