### ISSUE TITLE
Items being moved into filter of Adv. Demagnetizer when sorting with Inventory Tweaks Renewed

### ISSUE THREAD

**Issue by NielsPilgaard** [comp500/demagnetize#17]
Relayed from: https://github.com/NillerMedDild/Enigmatica6/issues/3373

When sorting using [Inventory Tweaks Renewed](https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed) while inside the Advanced Demagnetizer GUI, items are moved into the filter, effectively voiding them. 

Inventory Tweaks Renewed has a config that allows blacklisting certain inventories for sorting, but for some reason blacklisting `link.infra.demagnetize.blocks.DemagnetizerGui` does not prevent me from sorting.

**Comment by comp500** [comment]
Try blacklisting `DemagnetizerContainer` instead? I'll have a look at the code a bit more later, but that's the class that handles the inventory.

**Comment by NielsPilgaard** [comment]
Ah okay, I'll try that, thanks. I used a Quark config to print out the name, I guess it grabbed the wrong name :P

**Comment by NielsPilgaard** [comment]
That does work, thanks for the help!
