### ISSUE TITLE
Requesting Support for Quantum Flux And Pickle Tweaks

### ISSUE THREAD

**Issue by Thedrummonger** [comp500/Demagnetize#2]
This mod does not seem to work with the magnets from Quantum Flux and Pickle Tweaks. I was hoping compatibility could be added. Thanks!

**Comment by comp500** [comment]
I've submitted pull requests to both mod repos, [Quantum Flux](https://github.com/FantasyTeddy/QuantumFlux/pull/10) and [Pickle Tweaks](https://github.com/BlakeBr0/PickleTweaks/pull/23). Once they are merged this mod should work with them.

**Comment by comp500** [comment]
Both of these mods have now been updated to work with Demagnetize.
