### ISSUE TITLE
Demagnetizers prevent Ender IO’s vacuum chest from working

### ISSUE THREAD

**Issue by Dimentive** [comp500/Demagnetize#5]
The [vacuum chest](https://ftb.gamepedia.com/Vacuum_Chest) from [Ender IO](https://minecraft.curseforge.com/projects/ender-io) sucks items in and then puts them in its inventory. The demagnetizers from Demagnetize cause this Ender IO block to stop pulling items towards it and into its inventory. This ruins the canola setup that I was going for and forces me to use the [Solegnolia](https://ftb.gamepedia.com/Solegnolia) from [Botania](https://minecraft.curseforge.com/projects/botania) instead.

Demagnetizers may also prevent the [ranged collector](https://ftb.gamepedia.com/Ranged_Collector) from [Actually Additions](https://minecraft.curseforge.com/projects/actually-additions) from working as well, but I haven’t tested that.

#### Versions

* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Demagnetize:** 1.0.1 (latest)
* **Ender IO:** 5.0.40

**Comment by comp500** [comment]
You need to update to Ender IO version 5.0.43, see [this issue](https://github.com/SleepyTrousers/EnderIO/issues/4830#issuecomment-466082947) I made on the Ender IO repo. The original fix didn't work, but it was fixed later, however I didn't update Demagnetize's CurseForge description with the correct version (which has the fixed fix).

**Comment by Dimentive** [comment]
It’s good to hear that it’s already been fixed. I’ll update to the latest version of Ender IO right away. Thank you! 💙
