### ISSUE TITLE
[1.14.4] Change in Forge API

### ISSUE THREAD

**Issue by kwpugh** [comp500/Demagnetize#8]
The method getEntityData() is undefined for the type ItemEntity

Thought I would give you a heads up on this.

Using the latest Forge:  1.14.4 - 28.0.92

**Comment by comp500** [comment]
Do you think this is just a change in the name for the method, or do ItemEntities not store NBT anymore?

**Comment by comp500** [comment]
The method was renamed to `getPersistantData` in this commit: https://github.com/MinecraftForge/MinecraftForge/commit/e1863383ffbd7696a1e3d29bf7be07a1b6872794#diff-66531a6c0289a9654ce522f047a8827e
Thanks for the heads up!

**Comment by kwpugh** [comment]
I'll update accordingly.
