### ISSUE TITLE
[1.14.4] REQUEST: Mods tested and confirmed

### ISSUE THREAD

**Issue by kwpugh** [comp500/demagnetize#9]
Hi,

I tested your demagnetize mod with both my Gobber 2 and Ring of Attraction mods and can confirm they work as intended.

Can you add these mods to the list so others know?   

Thank you.

**Comment by comp500** [comment]
Will do! I already added them to the list on the Github readme, just didn't get round to adding them to Curseforge.

**Comment by comp500** [comment]
Done!

**Comment by kwpugh** [comment]
Thank you.
